web:
  upload-path: D:/file/
  fornt-path: D:/fornt/

server:
  port: 8011
  context-path: /zb
  session:
    timeout: 15

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
    type: com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: file:${web.upload-path},file:${web.fornt-path}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: net.zgysrc.zb.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
